name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Verify tag matches version
      run: |
        # Extract version from package
        PACKAGE_VERSION=$(python setup.py --version)
        # Extract version from git tag (strip 'v' prefix if present)
        GIT_TAG=${GITHUB_REF#refs/tags/}
        GIT_TAG=${GIT_TAG#v}
        # Check if versions match
        if [ "$PACKAGE_VERSION" != "$GIT_TAG" ]; then
          echo "Error: Package version ($PACKAGE_VERSION) does not match git tag ($GIT_TAG)"
          exit 1
        fi
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*