name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build twine  # 添加了 setuptools 和 wheel
    - name: Verify tag matches version
      run: |
        echo "Building package..."
        # Extract version from package
        PACKAGE_VERSION=$(python setup.py --version)
        echo "Package version: $PACKAGE_VERSION"
        # Extract version from git tag (strip 'v' prefix if present)
        GIT_TAG=${GITHUB_REF#refs/tags/}
        GIT_TAG=${GIT_TAG#v}
        echo "Git tag version: $GIT_TAG"
        # Check if versions match
        if [ "$PACKAGE_VERSION" != "$GIT_TAG" ]; then
          echo "Error: Package version ($PACKAGE_VERSION) does not match git tag ($GIT_TAG)"
          exit 1
        fi
        echo "Version verification successful"
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo "Building distribution packages..."
        python -m build
        echo "Verifying built packages..."
        twine check dist/*
        echo "Uploading to PyPI..."
        twine upload dist/* --verbose
        echo "Upload completed"